pub(crate) fn push_header(rust: &mut String) {
    rust.push_str("// @generated by lattice-codegen\n");
    rust.push_str("#[allow(unused_imports)]\nuse std::sync::Arc;\n");
    rust.push_str(
        "#[allow(unused_imports)]\nuse lattice_actor::handle::ActorHandle;
#[allow(unused_imports)]
use lattice_actor::registry::{ActorLoader, ActorRegistry};
#[allow(unused_imports)]
use lattice_actor::traits::{Actor, Handler};\n",
    );
    rust.push_str(
        "#[allow(unused_imports)]\nuse lattice_core::id::{ActorId, RouteKey};
#[allow(unused_imports)]
use lattice_core::kind::ActorKind;
#[allow(unused_imports)]
use lattice_core::actor_kind;\n",
    );
    rust.push_str(
        "#[allow(unused_imports)]\nuse lattice_gateway::error::GatewayError;\n#[allow(unused_imports)]\nuse lattice_gateway::frame::ClientFrame;\n#[allow(unused_imports)]\nuse lattice_gateway::route::{GatewayRouteTable, MessageRouter};\n",
    );
    rust.push_str(
        "#[allow(unused_imports)]\nuse lattice_placement::endpoint::EndpointLease;
#[allow(unused_imports)]
use lattice_placement::routing::rpc::EndpointRpcTransport;\n",
    );
    rust.push_str(
        "#[allow(unused_imports)]\nuse lattice_rpc::adapter::ActorRpcAdapter;
#[allow(unused_imports)]
use lattice_rpc::client::{TonicEndpointChannelPool, TypedRpcClient};
#[allow(unused_imports)]
use lattice_rpc::error::RpcError;
#[allow(unused_imports)]
use lattice_rpc::security::RpcServerSecurity;
#[allow(unused_imports)]
use lattice_rpc::traits::{RoutedRequest, RpcRequest, ShardedRpcCore};
#[allow(unused_imports)]
use lattice_rpc::types::{RoutedEnvelope, Rpc};\n",
    );
    rust.push_str("#[allow(unused_imports)]\nuse prost::Message as ProstMessage;\n\n");
}
