[package]
name = "lattice-actor-distributed"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
dashmap.workspace = true
futures-util.workspace = true
lattice-actor.workspace = true
lattice-model.workspace = true
lattice-remoting.workspace = true
prost.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
trybuild.workspace = true
