[package]
name = "lattice-actor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
concurrent-queue.workspace = true
event-listener.workspace = true
futures-util.workspace = true
lattice-model.workspace = true
lattice-actor-macros.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
trybuild.workspace = true
