#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProtoRouteKeyOption {
    pub actor_kind: String,
    pub key_field: String,
    pub key_type: RouteKeyType,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RouteKeyType {
    U64,
    I64,
    String,
    Bytes,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RpcMethodSpec {
    pub service_kind: String,
    pub service_name: String,
    pub method_name: String,
    pub request_type: String,
    pub reply_type: String,
    pub route_key: ProtoRouteKeyOption,
    pub gateway_msg_id: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedRpcBindings {
    pub rust: String,
}

pub fn generate_rpc_bindings(
    methods: &[RpcMethodSpec],
) -> Result<GeneratedRpcBindings, CodegenError> {
    validate_methods(methods)?;

    let mut rust = String::new();
    rust.push_str("// @generated by lattice-codegen\n");
    rust.push_str("use lattice_actor::{Actor, Handler};\n");
    rust.push_str(
        "use lattice_core::{ActorKind, RouteKey, ServiceKind, actor_kind, service_kind};\n",
    );
    rust.push_str("use lattice_gateway::ProstClientMessageBinding;\n");
    rust.push_str(
        "use lattice_rpc::{Rpc, RpcRequest, RoutedRequest, ShardedRpcCore, TypedRpcClient};\n\n",
    );

    for method in methods {
        push_routed_request(&mut rust, method);
        push_rpc_request(&mut rust, method);
        push_handler_assertion(&mut rust, method);
        push_typed_client(&mut rust, method);
        if method.gateway_msg_id.is_some() {
            push_gateway_binding(&mut rust, method);
        }
    }

    Ok(GeneratedRpcBindings { rust })
}

fn validate_methods(methods: &[RpcMethodSpec]) -> Result<(), CodegenError> {
    let mut msg_ids = std::collections::BTreeSet::new();
    for method in methods {
        if method.service_kind.trim().is_empty() {
            return Err(CodegenError::MissingField("service_kind"));
        }
        if method.service_name.trim().is_empty() {
            return Err(CodegenError::MissingField("service_name"));
        }
        if method.method_name.trim().is_empty() {
            return Err(CodegenError::MissingField("method_name"));
        }
        if method.request_type.trim().is_empty() {
            return Err(CodegenError::MissingField("request_type"));
        }
        if method.reply_type.trim().is_empty() {
            return Err(CodegenError::MissingField("reply_type"));
        }
        if method.route_key.actor_kind.trim().is_empty() {
            return Err(CodegenError::MissingField("route_key.actor_kind"));
        }
        if method.route_key.key_field.trim().is_empty() {
            return Err(CodegenError::MissingField("route_key.key_field"));
        }
        if let Some(msg_id) = method.gateway_msg_id
            && !msg_ids.insert(msg_id)
        {
            return Err(CodegenError::DuplicateGatewayMessageId { msg_id });
        }
    }
    Ok(())
}

fn push_routed_request(rust: &mut String, method: &RpcMethodSpec) {
    rust.push_str(&format!(
        "impl RoutedRequest for {request} {{\n",
        request = method.request_type
    ));
    rust.push_str("    fn actor_kind(&self) -> ActorKind {\n");
    rust.push_str(&format!(
        "        actor_kind!(\"{}\")\n",
        method.route_key.actor_kind
    ));
    rust.push_str("    }\n\n");
    rust.push_str("    fn route_key(&self) -> RouteKey {\n");
    rust.push_str(&format!("        {}\n", route_key_expr(&method.route_key)));
    rust.push_str("    }\n");
    rust.push_str("}\n\n");
}

fn push_rpc_request(rust: &mut String, method: &RpcMethodSpec) {
    rust.push_str(&format!(
        "impl RpcRequest for {request} {{\n",
        request = method.request_type
    ));
    rust.push_str(&format!("    type Reply = {};\n", method.reply_type));
    rust.push_str(&format!(
        "    const METHOD: &'static str = \"{}/{}\";\n",
        method.service_name, method.method_name
    ));
    rust.push_str("}\n\n");
}

fn push_handler_assertion(rust: &mut String, method: &RpcMethodSpec) {
    rust.push_str(&format!(
        "pub fn assert_{snake}_handler<A>()\n",
        snake = method.method_name.to_ascii_lowercase()
    ));
    rust.push_str("where\n");
    rust.push_str("    A: Actor + Handler<Rpc<");
    rust.push_str(&method.request_type);
    rust.push_str(">>,\n");
    rust.push_str("{\n");
    rust.push_str("}\n\n");
}

fn push_typed_client(rust: &mut String, method: &RpcMethodSpec) {
    let client_name = format!("{}Client", method.service_name);
    rust.push_str(&format!(
        "pub struct {client}<C> {{\n    inner: TypedRpcClient<C>,\n}}\n\n",
        client = client_name
    ));
    rust.push_str(&format!("impl<C> {client}<C>\n", client = client_name));
    rust.push_str("where\n    C: ShardedRpcCore,\n{\n");
    rust.push_str("    pub fn new(core: C) -> Self {\n        Self { inner: TypedRpcClient::new(core) }\n    }\n\n");
    rust.push_str(&format!(
        "    pub async fn {method}(&self, req: {request}) -> Result<{reply}, lattice_rpc::RpcError> {{\n",
        method = lower_camel_to_snake(&method.method_name),
        request = method.request_type,
        reply = method.reply_type
    ));
    rust.push_str("        self.inner.call(req).await\n");
    rust.push_str("    }\n");
    rust.push_str("}\n\n");
}

fn push_gateway_binding(rust: &mut String, method: &RpcMethodSpec) {
    let binding_name = format!(
        "{}{}GatewayBinding",
        method.service_name, method.method_name
    );
    rust.push_str(&format!("pub struct {};\n\n", binding_name));
    rust.push_str(&format!("impl {} {{\n", binding_name));
    rust.push_str("    pub fn binding() -> ProstClientMessageBinding<");
    rust.push_str(&method.request_type);
    rust.push_str("> {\n");
    rust.push_str(&format!(
        "        ProstClientMessageBinding::new({})\n",
        method.gateway_msg_id.expect("checked before codegen")
    ));
    rust.push_str("    }\n");
    rust.push_str("}\n\n");
}

fn route_key_expr(option: &ProtoRouteKeyOption) -> String {
    match option.key_type {
        RouteKeyType::U64 => format!("RouteKey::U64(self.{})", option.key_field),
        RouteKeyType::I64 => format!("RouteKey::I64(self.{})", option.key_field),
        RouteKeyType::String => format!("RouteKey::Str(self.{}.clone())", option.key_field),
        RouteKeyType::Bytes => format!("RouteKey::Bytes(self.{}.clone())", option.key_field),
    }
}

fn lower_camel_to_snake(value: &str) -> String {
    let mut output = String::new();
    for (index, ch) in value.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if index > 0 {
                output.push('_');
            }
            output.push(ch.to_ascii_lowercase());
        } else {
            output.push(ch);
        }
    }
    output
}

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum CodegenError {
    #[error("missing required codegen field {0}")]
    MissingField(&'static str),
    #[error("duplicate gateway message id {msg_id}")]
    DuplicateGatewayMessageId { msg_id: u32 },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_output_matches_phase_two_shape() {
        let generated = generate_rpc_bindings(&[world_enter_method()]).unwrap();

        assert_eq!(
            generated.rust,
            r#"// @generated by lattice-codegen
use lattice_actor::{Actor, Handler};
use lattice_core::{ActorKind, RouteKey, ServiceKind, actor_kind, service_kind};
use lattice_gateway::ProstClientMessageBinding;
use lattice_rpc::{Rpc, RpcRequest, RoutedRequest, ShardedRpcCore, TypedRpcClient};

impl RoutedRequest for EnterWorldRequest {
    fn actor_kind(&self) -> ActorKind {
        actor_kind!("World")
    }

    fn route_key(&self) -> RouteKey {
        RouteKey::U64(self.world_id)
    }
}

impl RpcRequest for EnterWorldRequest {
    type Reply = EnterWorldReply;
    const METHOD: &'static str = "WorldRpc/EnterWorld";
}

pub fn assert_enterworld_handler<A>()
where
    A: Actor + Handler<Rpc<EnterWorldRequest>>,
{
}

pub struct WorldRpcClient<C> {
    inner: TypedRpcClient<C>,
}

impl<C> WorldRpcClient<C>
where
    C: ShardedRpcCore,
{
    pub fn new(core: C) -> Self {
        Self { inner: TypedRpcClient::new(core) }
    }

    pub async fn enter_world(&self, req: EnterWorldRequest) -> Result<EnterWorldReply, lattice_rpc::RpcError> {
        self.inner.call(req).await
    }
}

pub struct WorldRpcEnterWorldGatewayBinding;

impl WorldRpcEnterWorldGatewayBinding {
    pub fn binding() -> ProstClientMessageBinding<EnterWorldRequest> {
        ProstClientMessageBinding::new(100)
    }
}

"#
        );
    }

    #[test]
    fn duplicate_gateway_msg_id_is_rejected() {
        let mut first = world_enter_method();
        let mut second = world_enter_method();
        first.request_type = "EnterWorldRequest".into();
        second.request_type = "MoveWorldRequest".into();

        let error = generate_rpc_bindings(&[first, second]).unwrap_err();

        assert_eq!(
            error,
            CodegenError::DuplicateGatewayMessageId { msg_id: 100 }
        );
    }

    fn world_enter_method() -> RpcMethodSpec {
        RpcMethodSpec {
            service_kind: "World".into(),
            service_name: "WorldRpc".into(),
            method_name: "EnterWorld".into(),
            request_type: "EnterWorldRequest".into(),
            reply_type: "EnterWorldReply".into(),
            route_key: ProtoRouteKeyOption {
                actor_kind: "World".into(),
                key_field: "world_id".into(),
                key_type: RouteKeyType::U64,
            },
            gateway_msg_id: Some(100),
        }
    }
}
