use std::fmt::Write;

use crate::error::CodegenError;
use crate::spec::{ActorProtocolSpec, InteractionMode};

pub fn render_actor_protocol(spec: &ActorProtocolSpec) -> Result<String, CodegenError> {
    spec.validate()?;
    let mut rust = String::from("// @generated by lattice-codegen; do not edit.\n\n");
    writeln!(rust, "lattice_actor::actor_protocol! {{").unwrap();
    writeln!(rust, "    {} {} {{", spec.visibility, spec.registrar_name).unwrap();
    writeln!(rust, "        protocol_id: {:#018x};", spec.protocol_id).unwrap();
    writeln!(rust, "        name: {:?};", spec.protocol_name).unwrap();
    for message in &spec.messages {
        match message.mode {
            InteractionMode::Tell => {
                writeln!(
                    rust,
                    "        tell {} => {} {{ schema_version: {}, codec: {} }}",
                    message.message_id,
                    message.message_type,
                    message.request_schema_version,
                    message.request_codec
                )
                .unwrap();
            }
            InteractionMode::Ask => {
                writeln!(
                    rust,
                    "        ask {} => {} {{ request_schema_version: {}, response_schema_version: {}, request_codec: {}, response_codec: {} }}",
                    message.message_id,
                    message.message_type,
                    message.request_schema_version,
                    message
                        .response_schema_version
                        .expect("validated response schema version"),
                    message.request_codec,
                    message
                        .response_codec
                        .as_deref()
                        .expect("validated response codec")
                )
                .unwrap();
            }
        }
    }
    rust.push_str("    }\n}\n");
    Ok(rust)
}
