mod actor_ref;
mod direct_link;
mod gateway;
mod header;
mod names;
mod request;
mod service;
mod tonic;
mod validation;

use crate::error::CodegenError;
use crate::spec::{GeneratedDirectLinkStreamSpec, ProtoMessageSpec, RpcMethodSpec};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedRpcBindings {
    pub rust: String,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct RenderOptions {
    pub actor_ref_proto: bool,
}

pub fn generate_rpc_bindings(
    methods: &[RpcMethodSpec],
) -> Result<GeneratedRpcBindings, CodegenError> {
    generate_rpc_bindings_with_options(methods, &[], RenderOptions::default())
}

pub fn generate_rpc_bindings_with_options(
    methods: &[RpcMethodSpec],
    messages: &[ProtoMessageSpec],
    options: RenderOptions,
) -> Result<GeneratedRpcBindings, CodegenError> {
    generate_rpc_bindings_with_direct_link_streams(methods, messages, options, &[])
}

pub fn generate_rpc_bindings_with_direct_link_streams(
    methods: &[RpcMethodSpec],
    messages: &[ProtoMessageSpec],
    options: RenderOptions,
    direct_link_streams: &[GeneratedDirectLinkStreamSpec],
) -> Result<GeneratedRpcBindings, CodegenError> {
    validation::validate_methods(methods)?;
    direct_link::validate_direct_link_streams(direct_link_streams)?;

    let mut rust = String::new();
    header::push_header(&mut rust);

    if options.actor_ref_proto {
        actor_ref::push_actor_ref_conversions(&mut rust);
    }
    direct_link::push_direct_link_messages(&mut rust, messages);
    direct_link::push_generated_direct_link_streams(&mut rust, direct_link_streams);
    for method in methods {
        if method.route_key_from_request {
            request::push_routed_request(&mut rust, method);
        }
        request::push_rpc_request(&mut rust, method);
    }
    let names = names::NameDisambiguation::new(methods);
    for service_methods in names::group_by_service(methods).values() {
        service::push_service_module(&mut rust, service_methods, &names);
    }
    tonic::push_tonic_endpoint_transport(&mut rust, methods);
    gateway::push_gateway_route_table(&mut rust, methods, &names);
    gateway::push_gateway_dispatcher(&mut rust, methods, &names);

    Ok(GeneratedRpcBindings { rust })
}

pub fn generate_direct_link_stream_bindings(
    streams: &[GeneratedDirectLinkStreamSpec],
) -> Result<GeneratedRpcBindings, CodegenError> {
    direct_link::validate_direct_link_streams(streams)?;
    let mut rust = String::new();
    rust.push_str("// @generated by lattice-codegen\n");
    direct_link::push_generated_direct_link_streams(&mut rust, streams);
    Ok(GeneratedRpcBindings { rust })
}
